version: '3'

services:
  db:
    container_name: practica-db
    image: postgres:13-alpine
    ports:
        - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./bd/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: practica-api
    build:
        context: ./api
        dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb
    ports:
      - "3080:3000"

  frontend:
    container_name: practica-front
    build:
        context: ./front
        dockerfile: ./Dockerfile
    ports:
      - "3081:80"
    depends_on:
      - api

