version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./bd/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
        context: ./api
        dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb
    ports:
      - "3080:3000"

  frontend:
    build:
        context: ./front
        dockerfile: ./Dockerfile
    ports:
      - "3081:80"
    depends_on:
      - api

